### ISSUE TITLE
마이페이지 정보 수정 관련

### ISSUE THREAD

**Issue by SejinHan25** [Bit159/withit#16]
@ecosky23 
마이페이지 정보 수정하면 로그아웃 됩니다. 
그리고 비밀번호 변경이 안됩니다.

**Comment by HJ-Rich** [comment]
1. 비번만 수정 > ok
2. 경력만 수정 > ok
3. 닉넴만 수정 > ok

4. 경력과 닉넴만 수정 > ok
5. 경력과 닉넴만 수정 > ok

6. 비번과 닉넴만 수정 > 비번ok 닉넴ok !!!경력이 0으로 초기화됨!!!
7. 셋다 수정 > 비번ok 닉네임ok  !!!경력이 0으로 초기화됨!!!


<iframe width="560" height="315" src="https://www.youtube.com/embed/Sc9aWvmqFtU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by ByungjooYang** [comment]
수정 완료

**Comment by HJ-Rich** [comment]
와우 대박~
감사합니다~!@ByungjooYang

**Comment by ByungjooYang** [comment]
@HJ-Rich 
memberMapper.xml 에 보니 #{myCareer} 이게 #{myCereer}로 오타가 나서 그런거였습니다 ㅠ

**Comment by HJ-Rich** [comment]
크헉 ㅠㅋㅋㅋㅋㅋ
저는 저렇게 분기가 나길래 복잡한 문제일줄 알고 ㅠㅠㅋㅋㅋㅋㅋ
