### ISSUE TITLE
세션 없이 /myPage 접근시 500에러

### ISSUE THREAD

**Issue by HJ-Rich** [Bit159/withit#21]
로그인창으로 이동되지 않고 500에러가 나오네요
![ezgif-7-1f5226118f93](https://user-images.githubusercontent.com/62681566/93885291-f20ce900-fd1e-11ea-9842-5373d0d8f5e3.gif)
@ByungjooYang 여유 되실때 한번 봐주실수 있을까요?!
바쁘시면 알려주시면 제가 한 번 보겠습니다!

**Comment by ByungjooYang** [comment]
해결 완료

**Comment by HJ-Rich** [comment]
수고하셨습니다 감사합니다 👍
